"""empty message

Revision ID: 01a48ae8f18c
Revises: 1d21c944f9a3
Create Date: 2018-02-19 17:47:37.395318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01a48ae8f18c'
down_revision = '1d21c944f9a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('in_use', sa.Boolean(), nullable=True))
    op.add_column('prev_doc', sa.Column('in_use', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prev_doc', 'in_use')
    op.drop_column('documents', 'in_use')
    # ### end Alembic commands ###
