"""empty message

Revision ID: 1d21c944f9a3
Revises: 21f8a12468ad
Create Date: 2018-02-19 17:25:47.561890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d21c944f9a3'
down_revision = '21f8a12468ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doc_path', sa.String(length=500), nullable=True),
    sa.Column('doc_name', sa.String(length=100), nullable=True),
    sa.Column('api_number', sa.String(length=12), nullable=True),
    sa.Column('test_date', sa.Date(), nullable=True),
    sa.Column('initial_pressure', sa.REAL(), nullable=True),
    sa.Column('final_pressure', sa.REAL(), nullable=True),
    sa.Column('buildup_pressure', sa.REAL(), nullable=True),
    sa.Column('comment', sa.String(length=1000), nullable=True),
    sa.Column('water_flow', sa.Boolean(), nullable=True),
    sa.Column('oil_flow', sa.Boolean(), nullable=True),
    sa.Column('scraped', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('scraper_name', sa.String(length=64), nullable=True),
    sa.Column('date_scraped', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_api_number'), 'documents', ['api_number'], unique=False)
    op.create_index(op.f('ix_documents_doc_name'), 'documents', ['doc_name'], unique=True)
    op.create_index(op.f('ix_documents_doc_path'), 'documents', ['doc_path'], unique=True)
    op.create_table('prev_doc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doc_path', sa.String(length=500), nullable=True),
    sa.Column('doc_name', sa.String(length=100), nullable=True),
    sa.Column('api_number', sa.String(length=12), nullable=True),
    sa.Column('test_date', sa.Date(), nullable=True),
    sa.Column('initial_pressure', sa.REAL(), nullable=True),
    sa.Column('final_pressure', sa.REAL(), nullable=True),
    sa.Column('buildup_pressure', sa.REAL(), nullable=True),
    sa.Column('comment', sa.String(length=1000), nullable=True),
    sa.Column('water_flow', sa.Boolean(), nullable=True),
    sa.Column('oil_flow', sa.Boolean(), nullable=True),
    sa.Column('scraped', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('scraper_name', sa.String(length=64), nullable=True),
    sa.Column('date_scraped', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prev_doc_api_number'), 'prev_doc', ['api_number'], unique=False)
    op.create_index(op.f('ix_prev_doc_doc_name'), 'prev_doc', ['doc_name'], unique=True)
    op.create_index(op.f('ix_prev_doc_doc_path'), 'prev_doc', ['doc_path'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prev_doc_doc_path'), table_name='prev_doc')
    op.drop_index(op.f('ix_prev_doc_doc_name'), table_name='prev_doc')
    op.drop_index(op.f('ix_prev_doc_api_number'), table_name='prev_doc')
    op.drop_table('prev_doc')
    op.drop_index(op.f('ix_documents_doc_path'), table_name='documents')
    op.drop_index(op.f('ix_documents_doc_name'), table_name='documents')
    op.drop_index(op.f('ix_documents_api_number'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
