"""Test Table

Revision ID: 28168a12f2c4
Revises: 24172655cf5d
Create Date: 2018-02-16 14:58:47.932478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28168a12f2c4'
down_revision = '24172655cf5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doc_path', sa.String(length=500), nullable=True),
    sa.Column('doc_name', sa.String(length=100), nullable=True),
    sa.Column('api_number', sa.String(length=12), nullable=True),
    sa.Column('test_date', sa.Date(), nullable=True),
    sa.Column('initial_pressure', sa.REAL(), nullable=True),
    sa.Column('final_pressure', sa.REAL(), nullable=True),
    sa.Column('buildup_pressure', sa.REAL(), nullable=True),
    sa.Column('water_flow', sa.Boolean(), nullable=True),
    sa.Column('oil_flow', sa.Boolean(), nullable=True),
    sa.Column('scraped', sa.Boolean(), nullable=True),
    sa.Column('scraper_name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_doc_name'), 'test', ['doc_name'], unique=True)
    op.create_index(op.f('ix_test_doc_path'), 'test', ['doc_path'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_doc_path'), table_name='test')
    op.drop_index(op.f('ix_test_doc_name'), table_name='test')
    op.drop_table('test')
    # ### end Alembic commands ###
